### ISSUE TITLE
Create MiniNAM instance in mininet python script

### ISSUE THREAD

**Issue by saurumesh** [uccmisl/MiniNAM#1]
Hi,

I'm facing an issue while trying to run MiniNAM gui for my mininet script. When I run my python script, it creates network, and then gives an error `ovs-vsctl: no bridge named s1`, `ovs-vsctl: no bridge named s2`

Here are the terminal logs
```
*** Creating network
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6653
Unable to contact the remote controller at 127.0.0.1:6633
Setting remote controller to 127.0.0.1:6653
*** Adding hosts:
h1 h2 h3 h4 h5 h6 h7 h8 r1 r2 r3 
*** Adding switches:
s1 s2 s3 s4 
*** Adding links:
(h1, s1) (h2, s1) (h3, s2) (h4, s2) (h5, s3) (h6, s3) (h7, s4) (h8, s4) (r1, r2) (r1, r3) (r2, s1) (r2, s2) (r3, s3) (r3, s4) 
*** Configuring hosts
h1 h2 h3 h4 h5 h6 h7 h8 r1 r2 r3 
*** Starting CLI:
ovs-vsctl: no bridge named s1
mininet> ovs-vsctl: no bridge named s2
ovs-vsctl: no bridge named s3
ovs-vsctl: no bridge named s4
```

**Python script code that I use to run with MiniNAM**
```python
def run():
    # Our Network object, and its initiation
    net = Mininet(
        topo=NetworkTopo(),
        controller=lambda name: RemoteController( name, ip='127.0.0.1' ),
        link=TCLink,
        switch=OVSKernelSwitch,
        autoSetMacs=True )

    mininam = MiniNAM(cheight=600, cwidth=1000 , net=net)
```

Please guide me through, if I'm missing anything

**Comment by akhalid3** [comment]
You are getting this error because you do not start your network instance before passing it to MiniNAM. That's why MiniNAM is unable to find your switches (or any other nodes in the network). Adding net.start(), after you are done setting up your network and are ready to call MiniNAM, will fix the issue.
